FROM jenkins/jenkins:lts-jdk11

# Install docker inside jenkins image
USER root
RUN apt update && \
    apt -y install apt-transport-https \
    curl \
    gnupg2 \
    software-properties-common && \
    curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg > /tmp/dkey; apt-key add /tmp/dkey && \
    add-apt-repository \
    "deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") \
    $(lsb_release -cs) \
    stable" && \
    apt update && \
    apt -y install docker-ce

# RUN groupadd docker
RUN usermod -a -G docker jenkins

# Install kubectl
RUN apt install ca-certificates

RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    chmod +x kubectl && \
    mv kubectl /usr/local/bin/

EXPOSE 8080