apiVersion: batch/v1
kind: Job
metadata:
  name: etcd-job
spec:
  template:
    metadata:
      name: etcd-job
    spec:
      containers:
      - name: etcd-job
        image: anldisr/etcdctl
        # env:
        #   - name: ETCDCTL_ENDPOINT
        #     value: 'http://example-etcd-cluster-client-service:2379'
        # command: ["etcdctl",  "mkdir", "pod-list"]
        command: ["etcdctl",  "--endpoints=http://host.docker.internal:2379", "put", "/pod-list", ""]
      restartPolicy: Never